### ISSUE TITLE
Reproduce the analysis

### ISSUE THREAD

**Issue by seabbs** [akira-endo/COVID19_clustersize#1]
This looks great! Looking forward to looking through in more detail later. 

Could you add some details of what is required to run the analysis? Planning on stepping through later as I read the draft :smile:

**Comment by akira-endo** [comment]
Updated the README.md to include dependencies info (hope this is what you meant). Thanks!

**Comment by seabbs** [comment]
Basically - missing what is needed for `.ipynb` (I may know but do others?)

**Comment by akira-endo** [comment]
Ah yes. Updated again

**Comment by seabbs** [comment]
Awesome
